//
//go:build ignore
// +build ignore

package main

import (
	"log"
	"os"
	"text/template"
	"time"
)

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
  // This file was generated by robots at
  // {{ .Timestamp }}
  package project

  func (o *{{.StructName}}) structFunction() string {
      return o.callAnotherFunction()
  }
`))

func main() {
	f, err := os.Create("struct_functions_generated.go")
	die(err)
	defer f.Close()

	packageTemplate.Execute(f, struct {
		Timestamp  time.Time
		StructName string
	}{
		Timestamp:  time.Now(),
		StructName: "MyStruct",
	})
}

func die(err error) {
	if err != nil {
		log.Fatal(err)
	}
}
