// Code generated by go generate; DO NOT EDIT.
  // This file was generated by robots at
  // 2023-11-28 10:25:01.430915 -0800 PST m=+0.001357543
  package project

  func (o *MyStruct) structFunction() string {
      return o.callAnotherFunction()
  }

